config/routes.rb
EmberRails::Application.routes.draw do
  namespace :api do
    namespace :v1 do
      resources :todos
    end
  end
  resources :todos

  root :to => 'application#home'
end

app/models/todo.rb
class Todo < ActiveRecord::Base
  attr_accessible :isCompleted, :title
end

app/controllers/api/v1/todos_controller.rb
class Api::V1::TodosController < ApplicationController

  respond_to :json

  def index
    respond_with Todo.all
  end

  def show
    respond_with Todo.find(params[:id])
  end

  def new
    respond_with Todo.new
  end

  def create
    @todo = Todo.new(params[:todo])
    respond_to do |format|
      if @todo.save
        format.json { render json: @todo, status: :created, location: @todo }
      else
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @todo = Todo.find(params[:id])
    respond_to do |format|
      if @todo.update_attributes(params[:todo])
        format.json { head :no_content }
      else
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @todo = Todo.find(params[:id])
    @todo.destroy
    respond_to do |format|
      format.json { head :no_content }
    end
  end
end

app/controllers/app_controller.rb
class AppController < ApplicationController
  def home
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  def home
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  # GET /todos
  # GET /todos.json
  def index
    @todos = Todo.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @todos }
    end
  end

  # GET /todos/1
  # GET /todos/1.json
  def show
    @todo = Todo.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @todo }
    end
  end

  # GET /todos/new
  # GET /todos/new.json
  def new
    @todo = Todo.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @todo }
    end
  end

  # GET /todos/1/edit
  def edit
    @todo = Todo.find(params[:id])
  end

  # POST /todos
  # POST /todos.json
  def create
    @todo = Todo.new(params[:todo])

    respond_to do |format|
      if @todo.save
        format.html { redirect_to @todo, notice: 'Todo was successfully created.' }
        format.json { render json: @todo, status: :created, location: @todo }
      else
        format.html { render action: "new" }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /todos/1
  # PUT /todos/1.json
  def update
    @todo = Todo.find(params[:id])

    respond_to do |format|
      if @todo.update_attributes(params[:todo])
        format.html { redirect_to @todo, notice: 'Todo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todos/1
  # DELETE /todos/1.json
  def destroy
    @todo = Todo.find(params[:id])
    @todo.destroy

    respond_to do |format|
      format.html { redirect_to todos_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/app_helper.rb
module AppHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/app/home.html.erb
<script type="text/x-handlebars" data-template-name="todos/index">
  <ul id="todo-list">
    {{#each itemController="todo"}}
    <li {{bind-attr class="isCompleted:completed isEditing:editing"}}>
    {{#if isEditing}}
    {{edit-todo class="edit" value=title focus-out="acceptChanges" insert-newline="acceptChanges"}}
    {{else}}
    {{input type="checkbox" checked=isCompleted class="toggle"}}
    <label {{action "editTodo" on="doubleClick"}}>{{title}}</label>
    <button {{action "removeTodo"}} class="destroy"></button>
    {{/if}}
    </li>
    {{/each}}
  </ul>
</script>

<script type="text/x-handlebars" data-template-name="todos">

<section id="todoapp">
  <header id="header">
    <h1>todos</h1>
    {{input type="text" id="new-todo" placeholder="What needs to be done?" value=newTitle action="createTodo"}}
  </header>

  <section id="main">
    {{outlet}}
    {{input type="checkbox" id="toggle-all" checked=allAreDone}}
  </section>

  <footer id="footer">
        <span id="todo-count">
          <strong>{{remaining}}</strong> {{inflection}} left
        </span>
    <ul id="filters">
      <li>
        {{#link-to "todos.index" activeClass="selected"}}All{{/link-to}}
      </li>
      <li>
        {{#link-to "todos.active" activeClass="selected"}}Active{{/link-to}}
      </li>
      <li>
        {{#link-to "todos.completed" activeClass="selected"}}Completed{{/link-to}}
      </li>
    </ul>

    {{#if hasCompleted}}
        <button id="clear-completed" {{action "clearCompleted"}}>
            Clear completed ({{completed}})
        </button>
    {{/if}}

  </footer>
</section>

<footer id="info">
  <p>Double-click to edit a todo</p>
</footer>

</script>

app/views/application/home.html.erb
<script type="text/x-handlebars" data-template-name="todos/index">
  <ul id="todo-list">
    {{#each itemController="todo"}}
    <li {{bind-attr class="isCompleted:completed isEditing:editing"}}>
    {{#if isEditing}}
    {{edit-todo class="edit" value=title focus-out="acceptChanges" insert-newline="acceptChanges"}}
    {{else}}
    {{input type="checkbox" checked=isCompleted class="toggle"}}
    <label {{action "editTodo" on="doubleClick"}}>{{title}}</label>
    <button {{action "removeTodo"}} class="destroy"></button>
    {{/if}}
    </li>
    {{/each}}
  </ul>
</script>

<script type="text/x-handlebars" data-template-name="todos">

<section id="todoapp">
  <header id="header">
    <h1>todos</h1>
    {{input type="text" id="new-todo" placeholder="What needs to be done?" value=newTitle action="createTodo"}}
  </header>

  <section id="main">
    {{outlet}}
    {{input type="checkbox" id="toggle-all" checked=allAreDone}}
  </section>

  <footer id="footer">
        <span id="todo-count">
          <strong>{{remaining}}</strong> {{inflection}} left
        </span>
    <ul id="filters">
      <li>
        {{#link-to "todos.index" activeClass="selected"}}All{{/link-to}}
      </li>
      <li>
        {{#link-to "todos.active" activeClass="selected"}}Active{{/link-to}}
      </li>
      <li>
        {{#link-to "todos.completed" activeClass="selected"}}Completed{{/link-to}}
      </li>
    </ul>

    {{#if hasCompleted}}
        <button id="clear-completed" {{action "clearCompleted"}}>
            Clear completed ({{completed}})
        </button>
    {{/if}}

  </footer>
</section>

<footer id="info">
  <p>Double-click to edit a todo</p>
  <%= link_to "Click here to see data on server",todos_path %>
</footer>

</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EmberRails</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag :all %>

  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "router" %>

  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>








</body>
</html>

app/views/todos/_form.html.erb
<%= form_for(@todo) do |f| %>
  <% if @todo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todo.errors.count, "error") %> prohibited this todo from being saved:</h2>

      <ul>
      <% @todo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :isCompleted %><br />
    <%= f.check_box :isCompleted %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/todos/edit.html.erb
<h1>Editing todo</h1>

<%= render 'form' %>

<%= link_to 'Show', @todo %> |
<%= link_to 'Back', todos_path %>

app/views/todos/index.html.erb
<h1>Listing todos</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Iscompleted</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @todos.each do |todo| %>
  <tr>
    <td><%= todo.title %></td>
    <td><%= todo.isCompleted %></td>
    <td><%= link_to 'Show', todo %></td>
    <td><%= link_to 'Edit', edit_todo_path(todo) %></td>
    <td><%= link_to 'Destroy', todo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Todo', new_todo_path %>

<br /><br />
<%= link_to "Click here to go back", root_path %>

app/views/todos/new.html.erb
<h1>New todo</h1>

<%= render 'form' %>

<%= link_to 'Back', todos_path %>

app/views/todos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @todo.title %>
</p>

<p>
  <b>Iscompleted:</b>
  <%= @todo.isCompleted %>
</p>


<%= link_to 'Edit', edit_todo_path(@todo) %> |
<%= link_to 'Back', todos_path %>